### ISSUE TITLE
论文从哪里可以下载啊

### ISSUE THREAD

**Issue by ghost** [oswaldoludwig/Human-Action-Recognition-with-Keras#10]
这篇论文从哪里可以下载啊

**Comment by oswaldoludwig** [comment]
如果你的意思是关于这项工作中使用的正则化方法的论文，它就在这里：
https://arxiv.org/abs/1604.06985
https://www.sciencedirect.com/science/article/pii/S0925231213008333

**Comment by oswaldoludwig** [comment]
如果你的意思是关于这项工作中使用的正则化方法的论文，它就在这里：
https://www.sciencedirect.com/science/article/pii/S0925231213008333
https://arxiv.org/abs/1604.06985

**Comment by oswaldoludwig** [comment]
如果你的意思是关于这项工作中使用的正则化方法的论文，它就在这里:
https://www.sciencedirect.com/science/article/pii/S0925231213008333
https://arxiv.org/abs/1604.06985

**Comment by ghost** [comment]
谢谢谢谢




------------------ 原始邮件 ------------------
发件人: "Oswaldo Ludwig"<notifications@github.com>;
发送时间: 2018年10月22日(星期一) 晚上7:37
收件人: "oswaldoludwig/Human-Action-Recognition-with-Keras"<Human-Action-Recognition-with-Keras@noreply.github.com>;
抄送: "1097425623"<1097425623@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [oswaldoludwig/Human-Action-Recognition-with-Keras] 论文从哪里可以下载啊 (#10)




如果你的意思是关于这项工作中使用的正则化方法的论文，它就在这里:
 https://www.sciencedirect.com/science/article/pii/S0925231213008333
 https://arxiv.org/abs/1604.06985
